name: Live_Source_Master

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v3

      - name: 2. 初始化环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. 安装必要插件
        run: pip install httpx

      - name: 4. 执行抓取脚本
        # 即使这里抓取部分失败，我们也尝试继续执行，看看能不能保留下卫视源
        run: python make_live.py

      - name: 5. 提交并同步
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cctv.m3u README.md
          # || exit 0 的意思是：如果没有新内容更新，也算执行成功，不要报红色错误
          git commit -m "自动同步最新直播源" || exit 0
          git push


