name: CCTV_Auto_Update

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时自动更新一次
  workflow_dispatch: # 允许你手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v3

      - name: 2. 初始化 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. 安装依赖
        run: pip install -r requirements.txt

      - name: 4. 执行抓取脚本
        run: python make_live.py

      - name: 5. 提交并同步到仓库
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cctv.m3u
          git commit -m "Update CCTV sources" || exit 0
          git push
